# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: B:/enel373/RxTimer/Nexys-4-DDR-Master.xdc

# Block Designs: bd/Reaction_Timer/Reaction_Timer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer || ORIG_REF_NAME==Reaction_Timer} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_finite_state_machine_0_0/Reaction_Timer_finite_state_machine_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_finite_state_machine_0_0 || ORIG_REF_NAME==Reaction_Timer_finite_state_machine_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_AnodeDecoder_0_0/Reaction_Timer_AnodeDecoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_AnodeDecoder_0_0 || ORIG_REF_NAME==Reaction_Timer_AnodeDecoder_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_0_0/Reaction_Timer_decade_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_0_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_1_0/Reaction_Timer_decade_counter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_1_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_1_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_2_0/Reaction_Timer_decade_counter_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_2_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_2_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_3_0/Reaction_Timer_decade_counter_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_3_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_3_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_DisplaySelector_0_0/Reaction_Timer_DisplaySelector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_DisplaySelector_0_0 || ORIG_REF_NAME==Reaction_Timer_DisplaySelector_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_clock_divider_0_0/Reaction_Timer_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_clock_divider_0_0 || ORIG_REF_NAME==Reaction_Timer_clock_divider_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_bcd_to_7seg_1_0/Reaction_Timer_bcd_to_7seg_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_bcd_to_7seg_1_0 || ORIG_REF_NAME==Reaction_Timer_bcd_to_7seg_1_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_clock_divider_1_0/Reaction_Timer_clock_divider_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_clock_divider_1_0 || ORIG_REF_NAME==Reaction_Timer_clock_divider_1_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_sevseg_mux_0_0/Reaction_Timer_sevseg_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_sevseg_mux_0_0 || ORIG_REF_NAME==Reaction_Timer_sevseg_mux_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_xlconstant_0_0/Reaction_Timer_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_xlconstant_0_0 || ORIG_REF_NAME==Reaction_Timer_xlconstant_0_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_xlconstant_1_0/Reaction_Timer_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_xlconstant_1_0 || ORIG_REF_NAME==Reaction_Timer_xlconstant_1_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_4_0/Reaction_Timer_decade_counter_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_4_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_4_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_5_0/Reaction_Timer_decade_counter_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_5_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_5_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_6_0/Reaction_Timer_decade_counter_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_6_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_6_0} -quiet] -quiet

# IP: bd/Reaction_Timer/ip/Reaction_Timer_decade_counter_7_0/Reaction_Timer_decade_counter_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Reaction_Timer_decade_counter_7_0 || ORIG_REF_NAME==Reaction_Timer_decade_counter_7_0} -quiet] -quiet

# XDC: b:/enel373/PersonalRXtimer/ReactionTimer/Reaction Timer.gen/sources_1/bd/Reaction_Timer/Reaction_Timer_ooc.xdc
